index:
    path: /weather/{day}
    controller: App\Controller\WeatherController::index
    defaults: { day: null }

calculator:
    path: /calculator
    controller: App\Controller\CalculatorController::index
