index:
    path: /weather/{day}
    controller: App\Controller\WeatherController::index
    defaults: { day: null }

age_calculator:
    path: /calculator
    controller: App\Controller\AgeCalculatorController::index
